/// Represents a user within the SnapLearn platform.
/// This model handles all three roles: student, instructor, and admin.
class UserProfile {
  /// Unique identifier
  final String id;

  /// Full name of the user
  final String displayName;

  /// Email address used for login and communications
  final String email;

  /// Optional URL to the user's avatar image
  final String? profileImageUrl;

  /// Defines access level: 'student', 'instructor', or 'admin'
  final String role;

  // --- Student Specific Fields ---

  /// List of course IDs the student is currently enrolled in
  final List<String> enrolledCourseIds;

  /// List of lesson/video IDs the student has finished watching
  final List<String> completedLessonIds;

  /// Categories or topics the user is interested in (used for feed recommendation)
  final List<String> interests;

  /// List of instructor IDs the user is following
  final List<String> followingIds;

  /// List of lesson IDs the user has saved for later viewing
  final List<String> savedLessonIds;

  /// List of lesson IDs the user has liked
  final List<String> likedLessonIds;

  // --- Admin/Moderation Fields ---

  /// If true, the user cannot log in or interact with the platform
  final bool isBlocked;

  /// If true, the account has been deactivated by an administrator
  final bool isDeleted;

  /// If true, the user is a verified instructor (receives a badge)
  final bool isVerified;

  /// Current subscription tier: e.g., 'free', 'premium'
  final String subscriptionType;

  // --- Instructor Specific Fields ---

  /// Current status of their application to become an instructor ('none', 'pending', 'approved', 'rejected')
  final String instructorApplicationStatus;

  /// Total revenue generated by the instructor from their courses
  final double totalEarnings;
  final int streakCount;
  final DateTime? lastLoginDate;
  final String? bio;
  final String? experience;
  final List<String> skills;

  // Constructor with default values for new users
  UserProfile({
    required this.id,
    required this.displayName,
    required this.email,
    this.profileImageUrl,
    this.role = 'student', // Default role is always student
    this.enrolledCourseIds = const [],
    this.completedLessonIds = const [],
    this.interests = const [],
    this.followingIds = const [],
    this.savedLessonIds = const [],
    this.likedLessonIds = const [],
    this.isBlocked = false,
    this.isDeleted = false,
    this.isVerified = false,
    this.subscriptionType = 'free',
    this.instructorApplicationStatus = 'none',
    this.totalEarnings = 0.0,
    this.streakCount = 0,
    this.lastLoginDate,
    this.bio,
    this.experience,
    this.skills = const [],
  });

  /// Factory constructor to create a `UserProfile` from a Map.
  factory UserProfile.fromMap(Map<String, dynamic> data) {
    return UserProfile(
      id: data['id'] ?? data['_id'] ?? '',
      displayName: data['displayName'] ?? '',
      email: data['email'] ?? '',
      profileImageUrl: data['profileImageUrl'],
      role: data['role'] ?? 'student',
      enrolledCourseIds: List<String>.from(data['enrolledCourseIds'] ?? []),
      completedLessonIds: List<String>.from(data['completedLessonIds'] ?? []),
      interests: List<String>.from(data['interests'] ?? []),
      followingIds: List<String>.from(data['followingIds'] ?? []),
      savedLessonIds: List<String>.from(data['savedLessonIds'] ?? []),
      likedLessonIds: List<String>.from(data['likedLessonIds'] ?? []),
      isBlocked: data['isBlocked'] ?? false,
      isDeleted: data['isDeleted'] ?? false,
      isVerified: data['isVerified'] ?? false,
      subscriptionType: data['subscriptionType'] ?? 'free',
      instructorApplicationStatus:
          data['instructorApplicationStatus'] ?? 'none',
      totalEarnings: (data['totalEarnings'] ?? 0.0).toDouble(),
      streakCount: data['streakCount'] ?? 0,
      lastLoginDate: data['lastLoginDate'] != null
          ? (data['lastLoginDate'] is String 
              ? DateTime.parse(data['lastLoginDate'])
              : data['lastLoginDate'])
          : null,
      bio: data['bio'],
      experience: data['experience'],
      skills: List<String>.from(data['skills'] ?? []),
    );
  }

  /// Converts the `UserProfile` instance back into a Map format.
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'displayName': displayName,
      'email': email,
      if (profileImageUrl != null) 'profileImageUrl': profileImageUrl,
      'role': role,
      'enrolledCourseIds': enrolledCourseIds,
      'completedLessonIds': completedLessonIds,
      'interests': interests,
      'followingIds': followingIds,
      'savedLessonIds': savedLessonIds,
      'likedLessonIds': likedLessonIds,
      'isBlocked': isBlocked,
      'isDeleted': isDeleted,
      'isVerified': isVerified,
      'subscriptionType': subscriptionType,
      'instructorApplicationStatus': instructorApplicationStatus,
      'totalEarnings': totalEarnings,
      'streakCount': streakCount,
      'lastLoginDate': lastLoginDate?.toIso8601String(),
      'bio': bio,
      'experience': experience,
      'skills': skills,
    };
  }

  UserProfile copyWith({
    String? displayName,
    String? email,
    String? profileImageUrl,
    String? role,
    List<String>? enrolledCourseIds,
    List<String>? completedLessonIds,
    List<String>? interests,
    List<String>? followingIds,
    List<String>? savedLessonIds,
    List<String>? likedLessonIds,
    bool? isBlocked,
    bool? isDeleted,
    bool? isVerified,
    String? subscriptionType,
    String? instructorApplicationStatus,
    double? totalEarnings,
    int? streakCount,
    DateTime? lastLoginDate,
    String? bio,
    String? experience,
    List<String>? skills,
  }) {
    return UserProfile(
      id: id,
      displayName: displayName ?? this.displayName,
      email: email ?? this.email,
      profileImageUrl: profileImageUrl ?? this.profileImageUrl,
      role: role ?? this.role,
      enrolledCourseIds: enrolledCourseIds ?? this.enrolledCourseIds,
      completedLessonIds: completedLessonIds ?? this.completedLessonIds,
      interests: interests ?? this.interests,
      followingIds: followingIds ?? this.followingIds,
      savedLessonIds: savedLessonIds ?? this.savedLessonIds,
      likedLessonIds: likedLessonIds ?? this.likedLessonIds,
      isBlocked: isBlocked ?? this.isBlocked,
      isDeleted: isDeleted ?? this.isDeleted,
      isVerified: isVerified ?? this.isVerified,
      subscriptionType: subscriptionType ?? this.subscriptionType,
      instructorApplicationStatus:
          instructorApplicationStatus ?? this.instructorApplicationStatus,
      totalEarnings: totalEarnings ?? this.totalEarnings,
      streakCount: streakCount ?? this.streakCount,
      lastLoginDate: lastLoginDate ?? this.lastLoginDate,
      bio: bio ?? this.bio,
      experience: experience ?? this.experience,
      skills: skills ?? this.skills,
    );
  }
}
